---
- name: copy over SLURM config
  hosts: all
  become: yes
  vars:
    slurm_conf_source_dir: "slurm"
    slurm_conf_dest_dir: "/etc/slurm-llnl"
    main_conf_owner: root
    main_conf_group: root

  tasks:
    - name: copy slurm.conf
      copy:
        src: "{{ slurm_conf_source_dir }}/slurm.conf"
        dest: "{{ slurm_conf_dest_dir }}"
        owner: "{{ main_conf_owner }}"
        group: "{{ main_conf_group }}"
        mode: '0644'
      notify:
        # This won't work for certain parameters that require actual
        # restarting of the daemons.
        #
        # - restart slurmd
        # - restart slurmctld
        - issue reconfigure command
    - name: copy slurmdbd.conf
      copy:
        src: "{{ slurm_conf_source_dir }}/slurmdbd.conf"
        dest: "{{ slurm_conf_dest_dir }}"
        owner: slurm
        group: slurm
        mode: '0600'
      notify:
        - restart slurmdbd
    - name: copy gres.conf
      copy:
        src: "{{ slurm_conf_source_dir }}/gres.conf"
        dest: "{{ slurm_conf_dest_dir }}"
        owner: "{{ main_conf_owner }}"
        group: "{{ main_conf_group }}"
        mode: '0644'
      notify:
        # - restart slurmd
        # - restart slurmctld
        - issue reconfigure command
    - name: copy cgroup.conf
      copy:
        src: "{{ slurm_conf_source_dir }}/cgroup.conf"
        dest: "{{ slurm_conf_dest_dir }}"
        owner: "{{ main_conf_owner }}"
        group: "{{ main_conf_group }}"
        mode: '0644'
      notify:
        # - restart slurmd
        # - restart slurmctld
        - issue reconfigure command
    - name: copy prolog
      copy:
        src: "{{ slurm_conf_source_dir }}/prolog"
        dest: "{{ slurm_conf_dest_dir }}"
        owner: "{{ main_conf_owner }}"
        group: "{{ main_conf_group }}"
        mode: '0755'
    - name: copy task_prolog
      copy:
        src: "{{ slurm_conf_source_dir }}/task_prolog"
        dest: "{{ slurm_conf_dest_dir }}"
        owner: "{{ main_conf_owner }}"
        group: "{{ main_conf_group }}"
        mode: '0755'

  handlers:
    # service automatically uses `systemd`
    - name: restart slurmd
      service:
        name: slurmd
        state: restarted
    - name: restart slurmctld
      service:
        name: slurmctld
        state: restarted
    - name: restart slurmdbd
      service:
        name: slurmdbd
        state: restarted
    - name: issue reconfigure command
      command: scontrol reconfigure
