---
- name: copy over SLURM config
  hosts: all
  become: yes
  become_method: sudo
  become_user: root
  vars:
    slurm_conf_dir: "/etc/slurm-llnl"
    owner: root
    group: root

  tasks:
    - name: copy slurm.conf
      copy:
        src: slurm/slurm.conf
        dest: "{{ slurm_conf_dir }}"
        owner: "{{ owner }}"
        group: "{{ group }}"
        mode: '0644'
      notify:
        - restart slurmd
        - restart slurmctld
    - name: copy slurmdbd.conf
      copy:
        src: slurm/slurmdbd.conf
        dest: "{{ slurm_conf_dir }}"
        owner: slurm
        group: slurm
        mode: '0600'
      notify:
        - restart slurmdbd
    - name: copy gres.conf
      copy:
        src: slurm/gres.conf
        dest: "{{ slurm_conf_dir }}"
        owner: "{{ owner }}"
        group: "{{ group }}"
        mode: '0644'
      notify:
        - restart slurmd
        - restart slurmctld
    - name: copy cgroup.conf
      copy:
        src: slurm/cgroup.conf
        dest: "{{ slurm_conf_dir }}"
        owner: "{{ owner }}"
        group: "{{ group }}"
        mode: '0644'
      notify:
        - restart slurmd
        - restart slurmctld
    - name: copy prolog
      copy:
        src: slurm/prolog
        dest: "{{ slurm_conf_dir }}"
        owner: "{{ owner }}"
        group: "{{ group }}"
        mode: '0755'
    - name: copy task_prolog
      copy:
        src: slurm/task_prolog
        dest: "{{ slurm_conf_dir }}"
        owner: "{{ owner }}"
        group: "{{ group }}"
        mode: '0755'

  handlers:
    # service automatically uses `systemd`
    - name: restart slurmd
      service:
        name: slurmd
        state: restarted
    - name: restart slurmctld
      service:
        name: slurmctld
        state: restarted
    - name: restart slurmdbd
      service:
        name: slurmdbd
        state: restarted
