---
- name: copy over SLURM config
  hosts:
    - submit
    - compute
    - controller
  gather_facts: no
  vars_files:
    - common_variables.yaml
  tasks:
    - name: ensure destination dir exists
      file:
        path: "{{ slurm_conf_dest_dir }}"
        state: directory
        owner: "{{ main_conf_owner }}"
        group: "{{ main_conf_group }}"
    - name: copy slurm.conf
      copy:
        src: "{{ slurm_conf_source_dir }}/slurm.conf"
        dest: "{{ slurm_conf_dest_dir }}"
        owner: "{{ main_conf_owner }}"
        group: "{{ main_conf_group }}"
        mode: "0444"
      notify:
        # This won't work for certain parameters that require actual
        # restarting of the daemons.
        #
        # - restart slurmd
        # - restart slurmctld
        - issue reconfigure command
    - name: copy gres.conf
      # TODO how to handle different compute nodes needing different GRES
      # specs?
      copy:
        src: "{{ slurm_conf_source_dir }}/gres.conf"
        dest: "{{ slurm_conf_dest_dir }}"
        owner: "{{ main_conf_owner }}"
        group: "{{ main_conf_group }}"
        mode: "0444"
      when: inventory_hostname in groups['compute']
      notify:
        # - restart slurmd
        # - restart slurmctld
        - issue reconfigure command
    - name: copy cgroup.conf
      copy:
        src: "{{ slurm_conf_source_dir }}/cgroup.conf"
        dest: "{{ slurm_conf_dest_dir }}"
        owner: "{{ main_conf_owner }}"
        group: "{{ main_conf_group }}"
        mode: "0444"
      when: inventory_hostname not in groups['submit']
      notify:
        # - restart slurmd
        # - restart slurmctld
        - issue reconfigure command
    - name: copy prolog
      copy:
        src: "{{ slurm_conf_source_dir }}/prolog"
        dest: "{{ slurm_conf_dest_dir }}"
        owner: "{{ main_conf_owner }}"
        group: "{{ main_conf_group }}"
        mode: "0755"
      # TODO when?
    - name: copy task_prolog
      copy:
        src: "{{ slurm_conf_source_dir }}/task_prolog"
        dest: "{{ slurm_conf_dest_dir }}"
        owner: "{{ main_conf_owner }}"
        group: "{{ main_conf_group }}"
        mode: "0755"
      when: inventory_hostname in groups['compute']

  handlers:
    - name: restart slurmd
      service:
        name: slurmd
        state: restarted
    - name: restart slurmctld
      service:
        name: slurmctld
        state: restarted
    - name: issue reconfigure command
      command: scontrol reconfigure

- name: copy over SLURM DB config
  hosts: db
  vars_files:
    - common_variables.yaml

  tasks:
    - name: ensure destination dir exists
      file:
        path: "{{ slurm_conf_dest_dir }}"
        state: directory
        owner: "{{ main_conf_owner }}"
        group: "{{ main_conf_group }}"
    - name: copy slurmdbd.conf
      copy:
        src: "{{ slurm_conf_source_dir }}/slurmdbd.conf"
        dest: "{{ slurm_conf_dest_dir }}"
        owner: slurm
        group: slurm
        mode: '0400'
      notify:
        # - restart slurmdbd
        - issue DB reconfigure command

  handlers:
    - name: restart slurmdbd
      service:
        name: slurmdbd
        state: restarted
    - name: issue DB reconfigure command
      command: sacctmgr reconfigure
