#!/usr/bin/env bash

# Implement automatic requeue behavior for jobs that exit with a return code
# of 99. Unlike the example given in
# https://slurm.schedmd.com/faq.html#reqspec, don't hold the job, resubmit it
# to run ASAP. Most logic adapted from
# https://bugs.schedmd.com/show_bug.cgi?id=1008.

{
    exitcode=${SLURM_JOB_EXIT_CODE2%:*}
    echo "$(date)    "$(for v in ${!SLURM_*} exitcode; do echo -n "${v}=${!v} "; done)
    if [[ "${exitcode}" == "99" ]]; then
        if [[ -z "${SLURM_ARRAY_JOB_ID}" ]]; then
            cmd="scontrol requeue ${SLURM_JOB_ID}"
        else
            cmd="scontrol requeue ${SLURM_ARRAY_JOB_ID}_${SLURM_ARRAY_TASK_ID}"
        fi
        eval "${cmd}"
        status=$?
        echo "${cmd} return code: ${status}"
        exit "${status}"
    fi
    echo "Done epilog $(date)"
} >> /var/log/slurm-llnl/slurmctld_epilog.log 2>&1
