#!/usr/bin/env bash

# export PATH=/bin:/home/slurm/linux/bin
# LOG=/home/slurm/linux/log/logslurmepilog
LOG=/tmp/logslurmepilog

echo "Start $(date)" >> ${LOG} 2>&1
echo "Job ${SLURM_JOB_ID} exitcode ${SLURM_JOB_EXIT_CODE2}" >> ${LOG} 2>&1
exitcode=$(echo "${SLURM_JOB_EXIT_CODE2}" | awk '{split($0, a, ":"); print a[1]}') >> ${LOG} 2>&1
if [[ "$exitcode" == "99" ]]; then
   echo "Found REQUEUE_EXIT_CODE: ${REQUEUE_EXIT_CODE}" >> ${LOG} 2>&1
   # scontrol requeuehold state=SpecialExit "${SLURM_JOB_ID}" >> ${LOG} 2>&1
   scontrol requeue "${SLURM_JOB_ID}" >> ${LOG} 2>&1
   echo $? >> ${LOG} 2>&1
else
   echo "Job ${SLURM_JOB_ID} exit all right" >> ${LOG} 2>&1
fi
echo "Done $(date)" >> ${LOG} 2>&1

exit 0
